server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

credorax:
  services:
    auditService:
#      name: consoleAuditService
#      name: fileAuditService
#      file: ./audit/audit.log
      name: databaseAuditService
    encryptionService:
      name: base64EncryptionService
#      name: defaultEncryptionService